name: Github Pages deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing dependencies
      run: |
        npm install

    - name: Building the application
      run: |
        npm run build

    - name: Authenticating with the repository
      run: | 
        git remote set-url origin https://afrigon:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Deploying on GitHub Pages
      run: |
        ./node_modules/gh-pages/bin/gh-pages.js -d build -u 'Github Actions <github@frigon.app>'

